### ISSUE TITLE
Intelligent Autocompletions: Styling

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#309]
Style the completions using colors from our pallette.

**Comment by curran** [comment]
This may or may not work, suggested by GPT:

```css
/* Style the completion tooltip container */
.cm-tooltip.cm-tooltip-autocomplete {
  border: 1px solid #888;
  background-color: #f8f8f8;
}

/* Style the individual completion items */
.cm-tooltip-autocomplete .cm-completionLabel {
  padding: 2px 10px;
  color: #555;
}

/* Style the selected completion item */
.cm-tooltip-autocomplete .cm-completionLabel.cm-completion-active {
  background-color: #0077cc;
  color: white;
}

```
