### ISSUE TITLE
Interactive Widgets for CSS

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#383]
As a developer editing a CSS file with VZCode, I want to be able to leverage the color picker and number dragger within CSS files.

Example CSS file:

```css
svg {
  background-color: #ff00ff;
}
line {
  stroke-width: 5px;
}
```
