### ISSUE TITLE
Color Picker should work in .css files

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#608]
As a user editing a CSS file with VZCode, I want to be able to use the Alt+ interactive widgets to edit numbers and colors.

Reproduction code:

```css
.ui-elements-container .counter {
  font-size: 32px; /* This number should be editable */
  color: #333333; /* This color should be editable */
  margin-left: 20px;
}
```
