### ISSUE TITLE
Minor spacing issues

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#765]
![image](https://github.com/vizhub-core/vzcode/assets/68416/5d5fcaf5-9f8e-4855-8c89-785de6f3481b)

```css
.files {
  margin-top: 6px;
}
.file-or-directory {
  margin: 0 6px; // Change from 8 to 6
}
.tab {
  border-top-left-radius: 4px; // Change from 8 to 4
  border-top-right-radius: 4px;
  padding: 4px 4px 4px 14px;
}
```
